# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: sqlite3
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: "file::memory:?cache=shared"

test:
  <<: *default
  database: "file::memory:?cache=shared"

production:
  <<: *default
  database: "file::memory:?cache=shared"
