services:
  sinatra:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/project
    working_dir: /project/sinatra_api
    environment:
      - PORT=3000
    command: bin/dev

  test:
    build: .
    volumes:
      - .:/project
    working_dir: /project
    command: bin/test
    profiles:
      - test
